development:
  username: <name>
  password: <pwd>
  url: jdbc:jtds:sqlserver://nwltest06n3:1433;integratedsecurity=true;domain=nwl;databaseName=logging

test:
  url: jdbc:sqlite:db/test.sqlite3

production:
  username: <name>
  password: <pwd>
  url: jdbc:jtds:sqlserver://nwltest06n3:1433;integratedsecurity=true;domain=nwl;databaseName=logging

